version: '2'
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=testing
      - MYSQL_PASSWORD=testing
      - MYSQL_DATABASE=testing
    volumes:
      - lamp_db:/var/lib/mysql

  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

volumes:
  lamp_db:
    driver: 'local'
